name: Build and deploy Node.js app to Azure Web App - prepace-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: Backend
        run: npm install

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3877FAE257F941AD9FE2FE8C228EC0BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D8C75D632AE43FDB1A45AC67E8B2D12 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0D91B32484894FE3BE1BBDDA7831CFBA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: prepace-backend
          slot-name: Production
          package: .
